#!/bin/bash
#set -x
glibcall_path="/home/ubt20/tools/glibc-all-in-one"

if [[ $# -eq 1 && $1 = '-l' ]]
then
	echo -e "\n what you have:\n"
	echo `ls ${glibcall_path}/libs`
	echo -e "\n what you can get:\n"
	cd ${glibcall_path}
	cat ./list

elif [[ $# -eq 1 && $1 = '-u' ]]
then
	cd ${glibcall_path}
	./update_list

elif [[ $# -eq 2 && $1 = '-i' ]]
then
	cd ${glibcall_path}
	./download $2

elif [[ $# -eq 3 && $1 = '-c' ]]
then
	libc_name=$2
	elf_path=$3
	libc_path="${glibcall_path}/libs/${libc_name}"
	if [ -f ${libc_path}/ld-[2].[0-9][0-9].so ]; then
	    patchelf --set-interpreter $libc_path/ld-[2].[0-9][0-9].so $elf_path
	fi
	if [ -f $libc_path/libc-[2].[0-9][0-9].so ]; then
	    patchelf --replace-needed libc.so.6 $libc_path/libc-[2].[0-9][0-9].so $elf_path
	fi


else
	echo -e "\nformat wrong!\n"
	echo -e "you can use like that:\n"
	echo -e "\tchglibc -l \t# to list glibc\n"
	echo -e "\tchglibc -u \t# to update list\n"
	echo -e "\tchglibc -i glibc \t# to install glibc\n"
	echo -e "\tchglibc -c libc_type filename\n"
fi
#set +x

